```{r}
stepdata <- read.csv("~/Programming/Reproducability/RepData_PeerAssessment1/activity.csv", header = TRUE, comment.char = "")

stepdata$datetime <- as.POSIXct(paste(stepdata$date, stepdata$interval%/%100, stepdata$interval%%100, sep = " "), "%Y-%m-%d %H %M", tz = "GMT")
stepdata$isna <- is.na(stepdata$steps)
```

```{r}
dailysteps <- tapply(stepdata$steps, stepdata$date, sum, na.rm = TRUE)
dailysteps <- as.data.frame(dailysteps)
dailysteps$isnas <- tapply(stepdata$isna, stepdata$date, sum)


hist(dailysteps$dailysteps[dailysteps$isnas < 288], breaks = 15)

mean(dailysteps$dailysteps)

median(dailysteps$dailysteps)

```

```{r}
timestep <- tapply(stepdata$steps, stepdata$interval, mean, na.rm = TRUE)
time <- as.integer(names(timestep))
time <- as.POSIXct(paste(time %/% 100, time %% 100, sep = " "),
                   "%H %M", tz = "GMT")


plot(time, timestep, type = "l", xaxt = "n",
     xlab = "Time of Day (hh:mm)", ylab = "5 Minute Step Average",
     main = "Average Daily Activity")
axis(1, at = as.POSIXct(c("00","6","12","18","24"), "%H", tz = "GMT"),
     labels = c("00:00","6:00","12:00","18:00","24:00"))

max <- which.max(timestep)

points(time[max], timestep[max], pch=1, col = "mediumblue")
text(time[max], timestep[max],
     paste("(",format(time[max], "%H:%M"), ", ", 
           round(timestep[max], 0), ")" ),
     pos=4 , cex = 0.67, col = "mediumblue")

cat("On average at ", format(time[max], "%H:%M"), " the maximum number of steps, ", round(timestep[max], 0), ", occurred.", sep = "")

```

